# Generated by Django 4.0 on 2022-01-03 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_administrador', to='proyecto_1.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_medico', to='proyecto_1.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('idPatologia', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Patol_Pac',
            fields=[
                ('idPatol_Pac', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_paciente', to='proyecto_1.paciente')),
                ('idPatologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patologia', to='proyecto_1.patologia')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutaImagen', models.CharField(max_length=200)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=4000)),
                ('Estado', models.CharField(max_length=3)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_administrador', to='proyecto_1.administrador')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_paciente', to='proyecto_1.paciente')),
            ],
        ),
    ]
